### PR TITLE
Updates from ESCOMP cam6_3_158 to cam6_4_041

### PR DESCRIPTION
**Pull request by gold2718**
This PR is needed to update Oslo Aero to adapt to the changes from ESCOMP/CAM.
The changes are all to CAM interface shadow files.

addresses NorESMhub/CAM#173

### CODE REVIEW

**Review by mvertens — APPROVED** [review]
I'm assuming that all of these changes are needed to satisfy the new cam7 interfaces - so these look fine to me.

**Comment by oyvindseland** [comment]
will look at it before noon today

**Comment by oyvindseland** [comment]
As far as I can see this should not change the results, except from specific output variables?

**Review by oyvindseland — APPROVED** [review]
I can not see any science problems in the code.

**Pull request merged**
